# Generated by Django 6.0.3 on 2026-03-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='scripture',
        ),
        migrations.AddField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
